application:
  applicationName: "review-web"
  deployment:
    imagePullSecrets: nexus-docker-config-forked
    additionalLabels:
      appCategory: "frontend"
    additionalPodAnnotations:
      sidecar.istio.io/inject: "true"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    podLabels:
      maistra.io/expose-route: "true"
    volumes: {}
    image:    
      # replaced by CI pipeline
      repository: IMAGE
      # replaced by CI pipeline     
      tag: TAG
    env:
    - name: PORT
      value: "4200"
    - name: REVIEW_API
      # This is hardcoded!
      value: "https://review-gabbar-dev.apps.binero-test.8sdzwd1l.kubeapp.cloud"
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
  service:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 4200
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true
  configMap:
   enabled: false
  route:
    enabled: true
    additionalLabels:
       router: default
  forecastle:
    enabled: true
    displayName: "Review Web"
    group: "Nordmart"
